### ISSUE TITLE
ELF files created by make_elf is too large

### ISSUE THREAD

**Issue by lieanu** [binjitsu/binjitsu#33]
The ELF file created by old `make_elf`, only 300+ bytes, 
But now elf file size is about  more than 2M.

**Comment by zachriggle** [comment]
Hey! Thanks for pointing this out, I thought I'd fixed everything back to the way it was.

The reason that this happened is that I was trying to make the load address for everything always be `0x10000000` by default so that the doctests would be nice and clean.  However, using `--section-start=` with `ld` really inflates the file size :(.
