### ISSUE TITLE
ELF files created by make_elf_from_assembly is too large

### ISSUE THREAD

**Issue by lieanu** [binjitsu/binjitsu#47]
Same as issues  [https://github.com/binjitsu/binjitsu/issues/33](https://github.com/binjitsu/binjitsu/issues/33)

But if I simply modify the 
`def make_elf_from_assembly(assembly, vma = 0x10000000):` to 
 `def make_elf_from_assembly(assembly, vma = None)`, 
the the vma start from `0x6000000`, not the same as the `make_elf` method which start from `0x1200000`.

**Comment by zachriggle** [comment]
For `make_elf_from_assembly`, we do not strip the ELF so that it includes debug symbols, and it's important that the starting address is the same every time.  

This is important so that future changes to the way that the sections are ordered (or some padding changes) do not change the addresses of symbols in the `.text` section.  Technically, this is not 100% necessary, but I don't want to have to worry about the changes in the future.

The only way to ensure that `_start` is at the address specified in `vma` is to bloat the size of the ELF by a large amount.

The size is only a small bit larger (4KB vs 230 bytes), so it shouldn't eat up too much disk space either.  Is there a reason that it needs to be samll for `make_elf_from_assembly`?

**Comment by lieanu** [comment]
4k is good， but in fact the size is about **2.1M**, the `step3` binary:

```
lieanu@ARCH : /tmp/pwn-asm-yQw6eR $ ls -alh 
total 2.1M
drwx------  2 lieanu users  100 Jul  7 08:27 .
drwxrwxrwt 23 root   root   960 Jul  7 08:27 ..
-rw-r--r--  1 lieanu users  148 Jul  7 08:27 step1
-rw-r--r--  1 lieanu users  824 Jul  7 08:27 step2
-rwxr-xr-x  1 lieanu users 2.1M Jul  7 08:27 step3
```

I create it using the following code:

```
    context.arch = "amd64"
    assembly = 'pop rax; ret; mov rbx, rax; ret; pop rcx; jmp rax;'
    rop = ROP(ELF.from_assembly(assembly))
```

**Comment by zachriggle** [comment]
Hmmm interesting


*Zach Riggle*

**Comment by zachriggle** [comment]
```
>>>     context.arch = "amd64"
>>>     assembly = 'pop rax; ret; mov rbx, rax; ret; pop rcx; jmp rax;'
>>>     rop = ROP(ELF.from_assembly(assembly))
[*] '/var/folders/hv/wnvzfp2d73b8cdxj7w_98tv0008rd2/T/pwn-asm-vNTKkN/step3'
    Arch:     amd64-64-little
    RELRO:    No RELRO
    Stack:    No canary found
    NX:       NX disabled
    PIE:      No PIE
[*] Loading gadgets for '/var/folders/hv/wnvzfp2d73b8cdxj7w_98tv0008rd2/T/pwn-asm-vNTKkN/step3'
>>> ls -la /var/folders/hv/wnvzfp2d73b8cdxj7w_98tv0008rd2/T/pwn-asm-vNTKkN/step3
-rwxr-xr-x  1 riggle  eng  4672 Jul  6 18:16 /var/folders/hv/wnvzfp2d73b8cdxj7w_98tv0008rd2/T/pwn-asm-vNTKkN/step3*
```

**Comment by lieanu** [comment]
Thanks. :+1:
